{% set name = "scrapy-contrib-bigexporters" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 977324c20c554f66cdcec178950cee2ede2dede920d64de82f032e571a0efb81

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
    - flit
  run:
    - python >=3.6
    - scrapy >=2.4.0

test:
  commands:
     - pip check
  requires:
     - pip
     - flit

about:
  home: https://github.com/ZuInnoTe/scrapy-contrib-bigexporters
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Scrapy exporter for Big Data formats'
  description: |
    scrapy-contrib-bigexporters provides additional exporters for Big Data and other formats for the web crawling and scraping framework Scrapy (https://scrapy.org).
  doc_url: https://github.com/ZuInnoTe/scrapy-contrib-bigexporters
  dev_url: https://github.com/ZuInnoTe/scrapy-contrib-bigexporters

extra:
  recipe-maintainers:
    - jornfranke
