{% set name = "scrapy-contrib-bigexporters" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name.replace('-', '_').lower() }}/{{ name.replace('-', '_').lower() }}-{{ version }}.tar.gz
  sha256: 394566bbca5904246f00332afbbd6f42012df185c684f89ef936f3da5bf80881

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit
  run:
    - python >={{ python_min }}
    - scrapy >=2.11.0

test:
  commands:
    - pip check
  requires:
    - pip
    - flit
    - python {{ python_min }}

about:
  home: https://codeberg.org/ZuInnoTe/scrapy-contrib-bigexporters
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Scrapy exporter for Big Data formats'
  description: |
    scrapy-contrib-bigexporters provides additional exporters for Big Data and other formats for the web crawling and scraping framework Scrapy (https://scrapy.org).
  doc_url: https://github.com/ZuInnoTe/scrapy-contrib-bigexporters
  dev_url: https://github.com/ZuInnoTe/scrapy-contrib-bigexporters

extra:
  recipe-maintainers:
    - jornfranke
